### ISSUE TITLE
Add backup tasks

### ISSUE THREAD

**Issue by HumanixSaektati** [Cinchoo/ChoEazyCopy#39] opened 2022-02-09 20:47 UTC
Hey,

would it be possible to integrate a backup task manager in the UI, so I don't have to manually add the profile file each time and can decide in the overview which task I want to start. So something like a backup software.

**Comment by HumanixSaektati** [comment] 2022-02-09 21:00
How do I imagine in the UI?

On the left side there is something free, you can add "Backup Tasks", similar to the other side (RoboCopy Options).

When I open the left side, I can choose the path where the "Backup Tasks" files are stored, the filename is the "Backup Tasks" name.

What is stored in the Backup Tasks files?
- Source Directory, Destionation Directory
- RoboCopy Command
- Comments can be added as plain text

**Comment by Cinchoo** [comment] 2022-02-13 02:44
Release v2.0.0.0-beta1 with this enhancement request. Pls give it try and let me know.

**Comment by HumanixSaektati** [comment] 2022-02-15 01:50
@Cinchoo 
Thank you. But I have found some problems.

- The timestamp name should use the same words as the standard file manager (see in File Explorer column) because it is more consistent. In this case of CREATED TIME -> DATE CREATED and LAST MODIFIED TIME -> DATE MODIFIED

- The column can be configured, that means in this case the timestamps can be hidden. only the task name can not be hidden, exactly the same behavior as File Explorer. Additionally there is the option "Size Column to Fit". 

- The performance is not smooth. I have only 3 .ezy files and I switched the files back and forth under "Backup Tasks" and it loads very slowly, it should be optimized to be stable, so resource efficient and it's loading speed  and saving speed should be seamless and fast. The speed and feel should be similar to File Explorer. I have tested with Windows 11.

- When I clone a task the Date Created timestamp for this file should be kept instead of being set to current time. Maybe there should be an option to decide if the 2 timestamps  (Created and Modified) should be kept or not when cloning. If the filename is too long, it cannot be displayed in the top overview bar. It comes then this. Only square icon. I think the overview bar should no longer show the filename. An extra path bar or something like that should be added.
![sdsd](https://user-images.githubusercontent.com/98705868/153976274-e7fa15a0-ecf4-419e-8629-82d4fd6614ea.PNG)

- It looks like ChoEazyCopy needs a design update. I have been using Windows regularly since Windows XP and my absolute favorite program is File Explorer, which I use incredibly much every day. Maybe it is an idea that ChoEazyCopy should go more in the direction of File Manager design. The look and feel should be a File Manager, but without displaying files and folders.

**Comment by Cinchoo** [comment] 2022-02-15 20:39
- The timestamp name should use the same words as the standard file manager (see in File Explorer column) because it is more consistent. In this case of CREATED TIME -> DATE CREATED and LAST MODIFIED TIME -> DATE MODIFIED
@Cinchoo, fixed

- The column can be configured, that means in this case the timestamps can be hidden. only the task name can not be hidden, exactly the same behavior as File Explorer. Additionally there is the option "Size Column to Fit".
@Cinchoo, added context menus to control the visibility of columns except task name column. Make all columns "Size Column to Fit" by default.

- The performance is not smooth. I have only 3 .ezy files and I switched the files back and forth under "Backup Tasks" and it loads very slowly, it should be optimized to be stable, so resource efficient and it's loading speed and saving speed should be seamless and fast. The speed and feel should be similar to File Explorer. I have tested with Windows 11.
@Cinchoo, addressed.

- When I clone a task the Date Created timestamp for this file should be kept instead of being set to current time. Maybe there should be an option to decide if the 2 timestamps (Created and Modified) should be kept or not when cloning.
@Cinchoo, added context menu to control them.

- If the filename is too long, it cannot be displayed in the top overview bar. It comes then this. Only square icon. I think the overview bar should no longer show the filename. An extra path bar or something like that should be added.
@Cinchoo, removed toolbar item. Moved the task name to window caption.

- It looks like ChoEazyCopy needs a design update. I have been using Windows regularly since Windows XP and my absolute favorite program is File Explorer, which I use incredibly much every day. Maybe it is an idea that ChoEazyCopy should go more in the direction of File Manager design. The look and feel should be a File Manager, but without displaying files and folders.
@Cinchoo, this will be major design change. For now, will keep this in shelf to consider in future.

Released [v2.0.0.0-beta2](https://github.com/Cinchoo/ChoEazyCopy/releases/tag/v2.0.0.0-beta2) with these requests. Pls give it try and let me know.

**Comment by Cinchoo** [comment] 2022-02-16 03:09
- The timestamp name should use the same words as the standard file manager (see in File Explorer column) because it is more consistent. In this case of CREATED TIME -> DATE CREATED and LAST MODIFIED TIME -> DATE MODIFIED
@Cinchoo, fixed

- The column can be configured, that means in this case the timestamps can be hidden. only the task name can not be hidden, exactly the same behavior as File Explorer. Additionally there is the option "Size Column to Fit".
@Cinchoo, added context menus to control the visibility of columns except task name column. Make all columns "Size Column to Fit" by default.

- The performance is not smooth. I have only 3 .ezy files and I switched the files back and forth under "Backup Tasks" and it loads very slowly, it should be optimized to be stable, so resource efficient and it's loading speed and saving speed should be seamless and fast. The speed and feel should be similar to File Explorer. I have tested with Windows 11.
@Cinchoo, addressed.

- When I clone a task the Date Created timestamp for this file should be kept instead of being set to current time. Maybe there should be an option to decide if the 2 timestamps (Created and Modified) should be kept or not when cloning.
@Cinchoo, added context menu to control them.

- If the filename is too long, it cannot be displayed in the top overview bar. It comes then this. Only square icon. I think the overview bar should no longer show the filename. An extra path bar or something like that should be added.
@Cinchoo, removed toolbar item. Moved the task name to window caption.

- It looks like ChoEazyCopy needs a design update. I have been using Windows regularly since Windows XP and my absolute favorite program is File Explorer, which I use incredibly much every day. Maybe it is an idea that ChoEazyCopy should go more in the direction of File Manager design. The look and feel should be a File Manager, but without displaying files and folders.
@Cinchoo, this will be major design change. For now, will keep this in shelf to consider in future.

Released [v2.0.0.0-beta2](https://github.com/Cinchoo/ChoEazyCopy/releases/tag/v2.0.0.0-beta2) with these requests. Pls give it try and let me know.

**Comment by HumanixSaektati** [comment] 2022-02-16 19:32
>  added context menus to control the visibility of columns except task name column. Make all columns "Size Column to Fit" by default.

According to my test, it is different from File Explorer. When I hide a column and show it again, the default size is used, which is the factory settings. File Explorer uses "Size Column to Fit" differently, I right click and click on "Size Column to Fit", then all columns are automatically fit. But I like the current solution too, it always uses the default setting.

>  removed toolbar item. Moved the task name to window caption.

It would be good if the filename is displayed more pleasantly in the window. It should not be too close to "Remember windows position/size" option, a bit more space and more symmetrical.

> this will be major design change. For now, will keep this in shelf to consider in future.

That would be very good, I recommend a symmetrical design and if you should add more language, I recommend to use more of Windows System. So it is possible for example to use other time formats and the column names are always identical to File Explorer.


> Released [v2.0.0.0-beta2](https://github.com/Cinchoo/ChoEazyCopy/releases/tag/v2.0.0.0-beta2) with these requests. Pls give it try and let me know.

Here new requests.

1:
When I hide the columns "Task Name", "Date Created" and "Date Modified" with the mouse (not via context menu), the column is completely empty and when I click on something in that field, ChoEazyCopy crashes. In File Explorer it is not possible to hide the column with the mouse (not via the context menu) and if the user tries to do so, the column name remains. 

2:
Unfortunately, when I move the mouse to a column, the column is not highlighted as it is in File Explorer.

3:
Under "Backup Tasks" it should be possible to select the tasks multiple times with the mouse and it will also be shown how much has been selected. Furthermore, it is also possible to delete the tasks multiple times instead of manually deleting them one by one.

4:
The "Control Panel" view should be remembered when starting ChoEazyCopy so similar to the option "Remember windows position/size". So it is possible that I can decide if I want to see Backup Tasks first or not. An option should be added e.g "Remember Control Panel position/size".

**Comment by Cinchoo** [comment] 2022-02-18 16:19
Managed to put fixes for all your requests. Released beta3. Try it and let me know.

Thanks for your help.

**Comment by HumanixSaektati** [comment] 2022-02-19 00:06
> Managed to put fixes for all your requests. Released beta3. Try it and let me know.

> 1:
When I hide the columns "Task Name", "Date Created" and "Date Modified" with the mouse (not via context menu), the column is completely empty and when I click on something in that field, ChoEazyCopy crashes. In File Explorer it is not possible to hide the column with the mouse (not via the context menu) and if the user tries to do so, the column name remains.

In the current beta version this only works for "Task Name", that the column when moved with the mouse remains also the column name and can not be made completely empty. For Date Created and Date Modified column it does not work, this should still be fixed.

> 2:
Unfortunately, when I move the mouse to a column, the column is not highlighted as it is in File Explorer.

> 3:
Under "Backup Tasks" it should be possible to select the tasks multiple times with the mouse and it will also be shown how much has been selected. Furthermore, it is also possible to delete the tasks multiple times instead of manually deleting them one by one.

> 4:
The "Control Panel" view should be remembered when starting ChoEazyCopy so similar to the option "Remember windows position/size". So it is possible that I can decide if I want to see Backup Tasks first or not. An option should be added e.g "Remember Control Panel position/size".

In the current beta version these features have not been added.

**Comment by HumanixSaektati** [comment] 2022-02-19 19:28
More problems found.

5;
Create more than 1 .ezy file with different Source Directory and Destination Directory. If under Backup Tasks another file is selected, the CHOOSE FOLDERS area is not automatically updated, it does not show the saved Source Directory and Destination Directory of the respective file. Only under ROBOCOPY COMMAND the path is displayed correctly.

6:
Create more than 1 .ezy file with different Source Directory and Destination Directory.
Select the first .ezy file and it will display for example this under ROBOCOPY COMMAND: RoboCopy.exe "C:\test" "C:\test2" *.* /E /COPY:DAT /MT:8

Select the second .ezy file and it will display for example this under ROBOCOPY COMMAND: RoboCopy.exe "C:\test3" "C:\test4" *.* /E /COPY:DAT /MT:8

Delete the first .ezy file with File Explorer. Now, under Backup Tasks, select the first .ezy file. There is no message that this file has been deleted and instead the results from the second file are displayed.

**Comment by Cinchoo** [comment] 2022-02-19 21:52
> 1:
When I hide the columns "Task Name", "Date Created" and "Date Modified" with the mouse (not via context menu), the column is completely empty and when I click on something in that field, ChoEazyCopy crashes. In File Explorer it is not possible to hide the column with the mouse (not via the context menu) and if the user tries to do so, the column name remains.

In the current beta version this only works for "Task Name", that the column when moved with the mouse remains also the column name and can not be made completely empty. For Date Created and Date Modified column it does not work, this should still be fixed.
@Cinchoo, yes this is issue. Will fix it on next release.

> 2:
Unfortunately, when I move the mouse to a column, the column is not highlighted as it is in File Explorer.
@Cinchoo, dont understand it. It is highlighting the row when I move the mouse over item. Below screenshot taken on my local.

![image](https://user-images.githubusercontent.com/9448455/154820203-4a7bb42e-0512-4125-9d9b-692334fae143.png)

> 3:
Under "Backup Tasks" it should be possible to select the tasks multiple times with the mouse and it will also be shown how much has been selected. Furthermore, it is also possible to delete the tasks multiple times instead of manually deleting them one by one.
@Cinchoo, well this has been taken care of differently. Instead of multiselect items and delete them at once, I came up with option 'Confirm on delete' (context menu) / Delete key combination, you can achieve to quickly delete items.

> 4:
The "Control Panel" view should be remembered when starting ChoEazyCopy so similar to the option "Remember windows position/size". So it is possible that I can decide if I want to see Backup Tasks first or not. An option should be added e.g "Remember Control Panel position/size".
@Cinchoo, no option introduced. Rather these settings are remembered automatically.

**Comment by Cinchoo** [comment] 2022-02-19 23:26
> More problems found.
> 
> 5; Create more than 1 .ezy file with different Source Directory and Destination Directory. If under Backup Tasks another file is selected, the CHOOSE FOLDERS area is not automatically updated, it does not show the saved Source Directory and Destination Directory of the respective file. Only under ROBOCOPY COMMAND the path is displayed correctly.
@Cinchoo, fixed
> 
> 6: Create more than 1 .ezy file with different Source Directory and Destination Directory. Select the first .ezy file and it will display for example this under ROBOCOPY COMMAND: RoboCopy.exe "C:\test" "C:\test2" _._ /E /COPY:DAT /MT:8
@Cinchoo, fixed
> 
> Select the second .ezy file and it will display for example this under ROBOCOPY COMMAND: RoboCopy.exe "C:\test3" "C:\test4" _._ /E /COPY:DAT /MT:8
> 
> Delete the first .ezy file with File Explorer. Now, under Backup Tasks, select the first .ezy file. There is no message that this file has been deleted and instead the results from the second file are displayed.
@Cinchoo, fixed

Take the v2.0.0.0-beta4, give it a try. Let me know if u encounter any other issues. Appreciate your help.

**Comment by HumanixSaektati** [comment] 2022-02-20 20:53
> ![image](https://user-images.githubusercontent.com/9448455/154822404-1ea5b80a-63f2-4ad3-bfbb-911db2c297d1.png)

This is what I mean, here is a screenshot of File Explorer on Windows 8, the column is highlighted.
![explorer_NoZCEY0qJO](https://user-images.githubusercontent.com/98705868/154863769-0488ee67-f02a-48e4-bd53-b34ad8f51574.png)

> well this has been taken care of differently. Instead of multiselect items and delete them at once, I came up with option 'Confirm on delete' (context menu) / Delete key combination, you can achieve to quickly delete items.

Is ok if you prefer this solution. The original idea was if you add multiselct items function via mouse as a base, you can later also add multiple copy/clone function.

> no option introduced. Rather these settings are remembered automatically.

It works only partially, when I exit and restart the software, the control panel is reset to default.

![1](https://user-images.githubusercontent.com/98705868/154863884-0ee89c78-02fd-4800-a373-1a1fb3e07e4e.PNG)
![2](https://user-images.githubusercontent.com/98705868/154863889-aae226aa-6891-41ee-9ad0-a10c7561a3fa.PNG)

**Comment by Cinchoo** [comment] 2022-02-20 22:55
Fixed both issues, released new version v2.0.0.0-beta5. Give it try and let me know. Thanks.

**Comment by HumanixSaektati** [comment] 2022-02-21 16:49
> Fixed both issues, released new version v2.0.0.0-beta5. Give it try and let me know. Thanks.

It looks good, just found some new problems now.

7: 
When create an .ezy file or save an existing .ezy file, it does not load automatically under Backup Tasks. I have to load it manually each time for it to be displayed or updated.

8: 
Sometimes when manually switching from Backup Tasks to RoboCopy Options there is a distortion of a few seconds as if something is loading in the background, this doesn't always happen and don't know exactly when it happens. Dometimes this also happens with the "Open".

9:
When clicking on "New" it loads a little too long for me, here should be optimized that it is more seamless.

10:
The only thing you could improve is the possibility to reset the control panel to default, so an option should be added so that users can decide for themselves if it should be saved automatically or not.

11:
When click on Donate button 2 web page appears in browser and one web page is not available anymore.

12:
Your supoort is much appreciated. -> Your support is much appreciated.

**Comment by Cinchoo** [comment] 2022-02-22 21:37
> > Fixed both issues, released new version v2.0.0.0-beta5. Give it try and let me know. Thanks.
> 
> It looks good, just found some new problems now.
> 
> 7: When create an .ezy file or save an existing .ezy file, it does not load automatically under Backup Tasks. I have to load it manually each time for it to be displayed or updated.
@Cinchoo, taken care of it. (added 'Watch for changes' context menu)
> 
> 8: Sometimes when manually switching from Backup Tasks to RoboCopy Options there is a distortion of a few seconds as if something is loading in the background, this doesn't always happen and don't know exactly when it happens. Sometimes this also happens with the "Open".
@Cinchoo, fixed.
> 
> 9: When clicking on "New" it loads a little too long for me, here should be optimized that it is more seamless.
@Cinchoo, fixed.
> 
> 10: The only thing you could improve is the possibility to reset the control panel to default, so an option should be added so that users can decide for themselves if it should be saved automatically or not.
@Cinchoo, added 'Reset' context menu to control panel.
> 
> 11: When click on Donate button 2 web page appears in browser and one web page is not available anymore.
@Cinchoo, can't reproduce it.
> 
> 12: Your supoort is much appreciated. -> Your support is much appreciated.
@Cinchoo, fixed.
> 
> 13: Copyright © 2015 -> Copyright © 2015-2022
@Cinchoo, fixed.
> 
> 14: Currently "Run" does not work anymore. According to the output, there is no destination directory, but a destination directory has been selected and the destination directory is the source directory. The source directory itself is not mentioned in the output.
@Cinchoo, fixed.
> 
> 15: Start ChoEazyCopy with more than 1 instance, preferably 3 or more. When starting you will notice that the loading process until the software is displayed takes a few seconds, this should be optimized. Now you see in Windows taskbar, the instances, all at the same time exit and this also takes a few seconds and the icons themselves are after the exit still for a few seconds to see in Windows taskbar, this should also be faster and more seamless.
@Cinchoo, fixed.

released new version v2.0.0.0-beta6. Try and let me know.

**Comment by auanasgheps** [comment] 2022-02-23 10:58
Hi, sorry to sneak in. I have a quick question regarding ChoEazyCopy.

I'm following this PR because I'm really interested in this new backup task feature.

My question is regarding file move.

If an existing file is moved on the source, will it be simply moved on the destination or will be deleted and recopied to the destination?

**Comment by HumanixSaektati** [comment] 2022-02-24 16:42
> Hi, sorry to sneak in. I have a quick question regarding ChoEazyCopy.
> 
> I'm following this PR because I'm really interested in this new backup task feature.
> 
> My question is regarding file move.
> 
> If an existing file is moved on the source, will it be simply moved on the destination or will be deleted and recopied to the destination?

As I understand your request you only want the files and folders to be moved in the target and not recopied and deleted, a good idea. Maybe the developer of ChoEazyCopy can say more about it, if such a function would like to integrate. You can create a new request.

**Comment by HumanixSaektati** [comment] 2022-02-24 17:09
>8: Sometimes when manually switching from Backup Tasks to RoboCopy Options there is a distortion of a few seconds as if something is loading in the background, this doesn't always happen and don't know exactly when it happens. Sometimes this also happens with the "Open".
@Cinchoo, fixed.

It has improved a bit, but sometimes there are still small delays when switching from Backup Tasks to RoboCopy Options. I have probably managed to reproduce it more accurately, start ChoEazyCopy and click immediately on RoboCopy Options, then you should see a short delay.

> 11: When click on Donate button 2 web page appears in browser and one web page is not available anymore.
@Cinchoo, can't reproduce it.

On my page these 2 web pages appear in my browser. The second web page is no longer available and in my browser appears this error message: Server not found.

1: https://www.paypal.com/donate/?token=N8bKOWfTthL2FT5kb7HjYuEEJxfI7iB7-oRsSoBvmz5_4ZN40xbW4J-IsIROvfs9670UuV3NLO21aq2N&locale.x=US

2: http://donation&currency_code=usd&bn=pp-donationsbf/

> 14: Currently "Run" does not work anymore. According to the output, there is no destination directory, but a destination directory has been selected and the destination directory is the source directory. The source directory itself is not mentioned in the output.
@Cinchoo, fixed.

On my side it doesn't work anymore, in output there is no source folder and destination directory anymore and I can't test further at the moment, because of a new problem, see at the end.

> 15: Start ChoEazyCopy with more than 1 instance, preferably 3 or more. When starting you will notice that the loading process until the software is displayed takes a few seconds, this should be optimized. Now you see in Windows taskbar, the instances, all at the same time exit and this also takes a few seconds and the icons themselves are after the exit still for a few seconds to see in Windows taskbar, this should also be faster and more seamless.
@Cinchoo, fixed.

The startup has improved it is about 1 second faster loading than before, but generally still slow because it takes about almost 4 seconds to see the user interface. I have an SSD and most of the software I launch finishes loading in about 1 to 2 seconds.
Quitting multiple instances looks the same on my side as it did in the previous version, when I quit the icons are not gone immediately, sometimes I have to manually mouse over the icons to make the icons in the windows task bar bar go away.

16: Currently I can't test further because of a new problem. I have manually deleted the path (I wanted this field to be empty) under Backup Tasks and whenever I start the software now, ChoEazyCopy always crashes.

**Comment by auanasgheps** [comment] 2022-02-24 17:16
> > Hi, sorry to sneak in. I have a quick question regarding ChoEazyCopy.
> > I'm following this PR because I'm really interested in this new backup task feature.
> > My question is regarding file move.
> > If an existing file is moved on the source, will it be simply moved on the destination or will be deleted and recopied to the destination?
> 
> As I understand your request, you only want the files and folders to be moved in the destination when they are also moved in the source, and not to delete and copy again, a good idea. Maybe the developer of ChoEazyCopy can say more about this if he wants to integrate such a feature. You can create a new request.

Your understanding is correct!
I have been using [FastCopy](https://fastcopy.jp/) to do simple backup tasks, but lately I discovered that moved files on source get deleted and re-copied on destination. Whilst this is ok on fast storage, can be a problem when using remote/slow storage or very large files. The same happens when a file is simply renamed on source.

I am looking for alternatives and hoping that ChoEazyCopy could accomplish the task!

**Comment by Cinchoo** [comment] 2022-02-25 23:03
> > 8: Sometimes when manually switching from Backup Tasks to RoboCopy Options there is a distortion of a few seconds as if something is loading in the background, this doesn't always happen and don't know exactly when it happens. Sometimes this also happens with the "Open".
> > @Cinchoo, fixed.
> 
> It has improved a bit, but sometimes there are still small delays when switching from Backup Tasks to RoboCopy Options. I have probably managed to reproduce it more accurately, start ChoEazyCopy and click immediately on RoboCopy Options, then you should see a short delay.
@Cinchoo, can't reproduce it.

> 
> > 11: When click on Donate button 2 web page appears in browser and one web page is not available anymore.
> > @Cinchoo, can't reproduce it.
> 
> On my page these 2 web pages appear in my browser. The second web page is no longer available and in my browser appears this error message: Server not found.
> 
> 1: https://www.paypal.com/donate/?token=N8bKOWfTthL2FT5kb7HjYuEEJxfI7iB7-oRsSoBvmz5_4ZN40xbW4J-IsIROvfs9670UuV3NLO21aq2N&locale.x=US
> 
> 2: http://donation&currency_code=usd&bn=pp-donationsbf/
> 
@Cinchoo, fixed

> > 14: Currently "Run" does not work anymore. According to the output, there is no destination directory, but a destination directory has been selected and the destination directory is the source directory. The source directory itself is not mentioned in the output.
> > @Cinchoo, fixed.
> 
> On my side it doesn't work anymore, in output there is no source directory and destination directory anymore and I can't test further at the moment, because of a new problem, see at the end.

@Cinchoo, would be great, if you can explain bit more with screenshots.

> 
> > 15: Start ChoEazyCopy with more than 1 instance, preferably 3 or more. When starting you will notice that the loading process until the software is displayed takes a few seconds, this should be optimized. Now you see in Windows taskbar, the instances, all at the same time exit and this also takes a few seconds and the icons themselves are after the exit still for a few seconds to see in Windows taskbar, this should also be faster and more seamless.
> > @Cinchoo, fixed.
>  
> The startup has improved it is about 1 second faster loading than before, but generally still slow because it takes about almost 4 seconds to see the user interface. I have an SSD and most of the software I launch finishes loading in about 1 to 2 seconds. Quitting multiple instances looks the same to me as it did in the previous version. When I quit, the icons are not gone immediately, sometimes I have to mouse over the icons for the icons in the Windows taskbar to be gone.
> 
@Cinchoo, I'm thinking it is something to do with Windows Taskbar behavior. Pls post screenshot.

> 16: Currently I can't test further because of a new problem. I have manually deleted the path (I wanted this field to be empty) under Backup Tasks and whenever I start the software now, ChoEazyCopy always crashes.
@Cinchoo, need more info pls. Post screen shots.

released new version v2.0.0.0-beta7. Try and let me know.

**Comment by HumanixSaektati** [comment] 2022-02-26 16:03
> On my side it doesn't work anymore, in output there is no source directory and destination directory anymore and I can't test further at the moment, because of a new problem, see at the end. 
@Cinchoo, would be great, if you can explain bit more with screenshots.

![sss](https://user-images.githubusercontent.com/98705868/155848831-c5dbda5d-1997-48d8-9375-2dc1cbf8c562.PNG)
![sssss](https://user-images.githubusercontent.com/98705868/155848834-86d4af83-5423-4c23-8ebb-8b65150c95b6.PNG)

When I test with the last offical version, v1.0.0.23, there are no problems.

> The startup has improved it is about 1 second faster loading than before, but generally still slow because it takes about almost 4 seconds to see the user interface. I have an SSD and most of the software I launch finishes loading in about 1 to 2 seconds. Quitting multiple instances looks the same to me as it did in the previous version. When I quit, the icons are not gone immediately, sometimes I have to mouse over the icons for the icons in the Windows taskbar to be gone. @Cinchoo, I'm thinking it is something to do with Windows Taskbar behavior. Pls post screenshot.


https://user-images.githubusercontent.com/98705868/155849707-1782b128-4145-4ca2-a88e-4da2b872ad90.mp4





> 16: Currently I can't test further because of a new problem. I have manually deleted the path (I wanted this field to be empty) under Backup Tasks and whenever I start the software now, ChoEazyCopy always crashes.
@Cinchoo, need more info pls. Post screen shots.

Here are the logs and screenshots. I did it this way. 1. Go to Backup Tasks and delete the path. This should be possible in general, if i want to have this field empty. 2. Quit the software and restart. 3. Then comes this. 
![fff](https://user-images.githubusercontent.com/98705868/155848704-6dcd78ed-0081-446c-a4ab-23ce6ee26adb.PNG)
![fgfd](https://user-images.githubusercontent.com/98705868/155848708-9e96bda7-0f02-480d-b706-316cc1d13537.PNG)
[ChoEazyCopy.exe.log](https://github.com/Cinchoo/ChoEazyCopy/files/8146890/ChoEazyCopy.exe.log)

**Comment by Cinchoo** [comment] 2022-02-26 16:47
> > On my side it doesn't work anymore, in output there is no source directory and destination directory anymore and I can't test further at the moment, because of a new problem, see at the end.
> 
> 
> When I test with the last offical version, v1.0.0.23, there are no problems.
> 
@Cinchoo, got it. Fixed the issue. 

> > The startup has improved it is about 1 second faster loading than before, but generally still slow because it takes about almost 4 seconds to see the user interface. I have an SSD and most of the software I launch finishes loading in about 1 to 2 seconds. Quitting multiple instances looks the same to me as it did in the previous version. When I quit, the icons are not gone immediately, sometimes I have to mouse over the icons for the icons in the Windows taskbar to be gone. @Cinchoo, I'm thinking it is something to do with Windows Taskbar behavior. Pls post screenshot.
> 
This is known windows OS issue. For your reference, attached a link talks about it.

https://answers.microsoft.com/en-us/windows/forum/all/tray-icon-does-not-disappear-when-the-program-is/9fcd4a50-bfa1-41e4-80de-93a14187d36d

> > 16: Currently I can't test further because of a new problem. I have manually deleted the path (I wanted this field to be empty) under Backup Tasks and whenever I start the software now, ChoEazyCopy always crashes.
> > @Cinchoo, need more info pls. Post screen shots.
> 
> Here are the logs and screenshots. I did it this way. 1. Go to Backup Tasks and delete the path. This should be possible in general, if i want to have this field empty. 2. Quit the software and restart. 3. Then comes this. 

@Cinchoo, got it. Fixed the issue.

released new version v2.0.0.0-beta8. Try and let me know. Thanks again for your help.

**Comment by HumanixSaektati** [comment] 2022-02-26 19:09
> released new version v2.0.0.0-beta8. Try and let me know. Thanks again for your help.
From my side I have not found any new problems. Except that starting the software is not finished loading in 1.5 to 2 seconds. Currently it takes 3.7 seconds to 4 seconds, I measured with a stopwatch app. The same behavior when exiting the software, it takes about 1.5 seconds to 2 seconds until it is completely gone.

When I test other Windows software, like Notepad++ it is much faster, it takes 0.5 to 1 seconds when it starts or quits. Can you optimize it so that it almost feels like a native application?

**Comment by HumanixSaektati** [comment] 2022-02-26 23:14
> Great, this one last issue requires sometime to investigate. Pls raise a separate ticket, will get to that later.

Done.

**Comment by Cinchoo** [comment] 2022-02-28 21:34
Pls close this when u can.

**Closed** 2022-03-01 03:10 UTC
Labels: enhancement
